name = "VDJDL"
uuid = "044a11ef-8b51-4543-8111-feb298e77431"
authors = ["Mateusz Kaduk <mateusz.kaduk@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
